# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: violations
  view:
    formats: { json: true, xml: false, rss: false }
    view_response_listener: true
  serializer:
    serialize_null: true
  format_listener:
    rules:
      - { path: '^/', priorities: [ 'json' ], fallback_format: 'json' }
  param_fetcher_listener: force
  exception:
    enabled: true
    map_exception_codes: true
    codes:
      { App\Exception\ResourceValidationException: 400, App\Exception\ForbiddenException: 403 }
    messages:
      {
        App\Exception\ResourceValidationException: true,
        App\Exception\ForbiddenException: true,
        Symfony\Component\HttpKernel\Exception\NotFoundHttpException: true
      }
